name: terraform

on:
  pull_request:
    paths:
      - "infra/**"

jobs:
  plan:
    name: plan (${{ matrix.env }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
    defaults:
      run:
        working-directory: infra/envs/${{ matrix.env }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.0"

      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -refresh=false
